# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('project_description', models.TextField(max_length=500)),
                ('worked_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_links', models.URLField()),
                ('social_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
