# Generated by Django 2.0.4 on 2018-04-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onePgFolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appreciate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
