# Generated by Django 2.0.4 on 2018-04-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onePgFolio', '0002_appreciate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciate',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
