# Generated by Django 2.0.4 on 2018-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onePgFolio', '0003_auto_20180424_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='get_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('remarks', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='co_name',
            field=models.CharField(help_text='Enter company name', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='designation',
            field=models.CharField(help_text='Enter your designation there', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='project_description',
            field=models.TextField(help_text='Care to describe what you did there..', max_length=500),
        ),
    ]
